### ISSUE TITLE
Enable Google Analytics 4 (GA4) for docs.fluentbit.io

### ISSUE THREAD

**Issue by chalin** [fluent/fluent-bit-docs#1002]
For the main tracking issue, and context for this request, see:

- https://github.com/fluent/fluent-bit-website-hugo/issues/22

Related / similar request for another GitBook:

- https://github.com/fluent/fluentd-docs-gitbook/issues/437

/cc @caniszczyk @nate-double-u @toru-takahashi

**Comment by patrick-stephens** [comment]
What needs updating @chalin ? I'm not an expert on Gitbook or analytics but if you let me know what to do I can tackle it.
