### ISSUE TITLE
Instructions for setting up vivo exporter plugin is not clear

### ISSUE THREAD

**Issue by nilushancosta** [fluent/fluent-bit-docs#1125]
I want to setup Fluent Bit + Vivo exporter plugin in Kubernetes. My goal is to query logs from the Vivo exporter endpoint.

The [Vivo exporter document](https://docs.fluentbit.io/manual/pipeline/outputs/vivo-exporter) states that "this plugin aims to be used in conjunction with Vivo project".
So I installed Vivo in addition to Fluent Bit. But when I checked the Vivo project deployment, I noticed that it also deploys a Fluent Bit instance. Therefore would installing only Vivo be enough?

The configuration for Fluent Bit running within Vivo is copied to the Docker image at build time - https://github.com/calyptia/vivo/blob/1f6c929b93fcc69a6d05a0b4ca38ef7db6480acf/service/Dockerfile#L23
Therefore to use the configuration in https://docs.fluentbit.io/manual/pipeline/outputs/vivo-exporter#getting-started, do we need to rebuild the vivo Docker image? Or can we configure the Fluent Bit deployement runing outside of Vivo?

**Comment by patrick-stephens** [comment]
https://github.com/calyptia/vivo/blob/master/vivo-deployment.yaml may be useful but there are a few things still to resolve, it needs to proxy via localhost to get data so will not work without port-forwarding locally:
```shell
kubectl port-forward svc/calyptia-vivo 8000:8000 2025:2025
```

**Comment by patrick-stephens** [comment]
The latest (3.0.1) Vivo containers should all work fine now. To use them you need to send data via `forward` to the input in the container. Fluent Bit receives it and exports it to the Vivo UI.
