### ISSUE TITLE
Documentation nitpicks

### ISSUE THREAD

**Issue by HereComesTheMoon** [fluent/fluent-bit-docs#1196]
I'm currently reading up on Fluentbit and noticed the following minor issues while reading up on it in the documentation. I put them here for your consideration. I might find other ones later.

1. [Here](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit) it claims that "YAML configuration is tech preview so not recommended for production.", but [here](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml)  there is the claim that "YAML configuration feature was introduced since FLuent Bit version 1.9 as experimental, and it is production ready since Fluent Bit 2.0."
2. [This page](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/format-schema) claims that "Multiple keys with the same name can exist." It's unclear how these are handled—even a short sentence explaining this would be valuable. 
3. https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/format-schema and https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file use the same key names (eg. daemon, log_level), but there doesn't appear to be any mention of case sensitivity on either page. This is confusing. This is especially bad when combined with the 'multiple keys' thing. If I define log_level and Log_Level, do I define two different keys or the same one twice? 

Have a great week.

**Comment by lecaros** [comment]
Hello @HereComesTheMoon,
thanks for reporting this.
Would you like to submit a PR for these?

**Comment by endersonmaia** [comment]
PR sent for `1.` at #1201

**Comment by HereComesTheMoon** [comment]
I'd like that, but I'd have to discuss the legalities of the matter with my current employer. I'm fairly new, and we have rules related to open source, so I'd have to figure that out first.
