### ISSUE TITLE
Divergent information about YAML Configuation

### ISSUE THREAD

**Issue by endersonmaia** [fluent/fluent-bit-docs#1200]
> YAML configuration is tech preview so not recommended for production.

From: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit

> YAML configuration feature was introduced since FLuent Bit version 1.9 as experimental, and it is production ready since Fluent Bit 2.0.

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit

**Comment by lecaros** [comment]
Hello @endersonmaia,
we also received a report of this in https://github.com/fluent/fluent-bit-docs/issues/1196.
PRs are most welcome!

**Comment by endersonmaia** [comment]
Sorry for not seeing the issues first.

I can send a PR, was just checking what's the correct statement.
