### ISSUE TITLE
Docs for oracle log analytics plugin not published

### ISSUE THREAD

**Issue by adiforluls** [fluent/fluent-bit-docs#1219]
The documentation was merged for oracle log analytics plugin https://github.com/fluent/fluent-bit-docs/pull/1186 but I don't see the content in the public docs. Is there something missing or something needs to be done to publish new docs?
cc: @patrick-stephens

**Comment by lecaros** [comment]
Hi @adiforluls,
It must be added to SUMMARY.md as well. If you submit the PR we'll take care of it.

**Comment by patrick-stephens** [comment]
https://docs.fluentbit.io/manual/pipeline/outputs/oci-logging-analytics
