### ISSUE TITLE
Unit Tests documentation is out of date

### ISSUE THREAD

**Issue by vlvasilev** [fluent/fluent-bit-docs#135]
When I was trying to write my own unit test I found that the unit test documentation is out of date.
First I had to set `-DFLB_TESTS_RUNTIME=ON` instead of `-DFLB_TESTS=ON` and after that, I had to run `make` before entering `make test` because the binaries were missing

**Comment by edsiper** [comment]
thanks for reporting the problem. Doc fixed in the git repo
