### ISSUE TITLE
[filter_parser] preserve_key and reserve_data documentation incorrect

### ISSUE THREAD

**Issue by jamesgoodhouse** [fluent/fluent-bit-docs#151]
The documentation for how to use the preserve_key and reserve_data options for the parser filter incorrectly show configuring the actual parser with these options and not the filter parser which is where they actually belong.

**Comment by edsiper** [comment]
hmm I don't see the error, would you please point me out what's wrong ? or maybe it got fixed recently ?

https://docs.fluentbit.io/manual/filter/parser

**Comment by lecaros** [comment]
solved in https://github.com/fluent/fluent-bit-docs/pull/173
