### ISSUE TITLE
fiter_stdout is missing 

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit-docs#16]
A document about filter_stdout is missing.

**Comment by edsiper** [comment]
indeed I am thinking if it having that filter is helpful or not.

**Comment by nokute78** [comment]
Hmm, it is enough to use out_stdout in functionality.

But it is helpful to implement filter plugins.
Filter_stdout is simplest of filter plugins.

**Comment by nokute78** [comment]
It was fixed by #17
