### ISSUE TITLE
Conditionally disable plugin

### ISSUE THREAD

**Issue by rashmichandrashekar** [fluent/fluent-bit-docs#161]
Is it possible to disable/enable the tail plugin based on an evironment varibale or an other setting?
I want to be do this for the tail plugin to customize the log tailing.

**Comment by edsiper** [comment]
Upon build time, certain plugins are enabled or disabled by default. If you want to disable the tail input plugin you can use the following cmake option:

```
$ cmake -DFLB_INPUT_TAIL=off ../
```
