### ISSUE TITLE
BUG - Wrong table rendering in GitBook

### ISSUE THREAD

**Issue by kvolkovich-sc** [fluent/fluent-bit-docs#166]
https://fluentbit.io/documentation/0.14/filter/nest.html

![Screen Shot 2019-05-16 at 4 34 16 PM](https://user-images.githubusercontent.com/24652543/57857934-c9a2df80-77f8-11e9-8754-5ac6cb372f7a.png)

**Comment by edsiper** [comment]
this is fixed in newest versions of the docs:

https://docs.fluentbit.io/manual/filter/nest
