### ISSUE TITLE
Stream processor page missing

### ISSUE THREAD

**Issue by dperetti** [fluent/fluent-bit-docs#167]
According to the [accouncements](https://fluentbit.io/announcements/v1.1.0/) page, there is a new Stream Processor input.
It links to a page that doesn't exist (https://docs.fluentbit.io/manual/input/stream_processor/).

**Comment by edsiper** [comment]
The current link is referring to: https://docs.fluentbit.io/stream-processing/

additional config by file: https://docs.fluentbit.io/manual/configuration/stream_processor
