### ISSUE TITLE
detail on how the fields are being written into the output plugin and how to add or modify one

### ISSUE THREAD

**Issue by viveksinghggits** [fluent/fluent-bit-docs#170]
If we talk specifically about `systemd`  as input plugin and `es` as ouput pluging. Below are all the fields that being written to the elastic search cluster
```
@timestamp
CONTAINER_ID
CONTAINER_ID_FULL
CONTAINER_NAME
CONTAINER_TAG
MESSAGE
PRIORITY
_BOOT_ID
_CAP_EFFECTIVE
_CMDLINE
_COMM
_EXE
_GID
_HOSTNAME
_MACHINE_ID
_PID
_SELINUX_CONTEXT
_SOURCE_REALTIME_TIMESTAMP
_SYSTEMD_CGROUP
_TRANSPORT
_UID
_id
_index
_score
_type
```
among the fields above below are all the fields that are being generated by `journald` itself
```
CONTAINER_ID
CONTAINER_ID_FULL
CONTAINER_NAME
CONTAINER_TAG
MESSAGE
```
Now my suggestion is to have more details on how the other fields are being generated and how can be add or modify one, and we should have it documented on the docs somewhere.

**Comment by edsiper** [comment]
Normally we don't document the source fields of every input plugin, we have more than 20 input plugins.

The getting started section of our docs explains how filtering works for data modifications if you have more ideas to make it better we are open to receive your pull requests with improvements.

refs: https://docs.fluentbit.io/manual/getting_started
