### ISSUE TITLE
Config option Mem_Buf_Limit should be documented for systemd input

### ISSUE THREAD

**Issue by johlo** [fluent/fluent-bit-docs#178]
We experienced situations where fluent-bit OOM'd with the systemd input plugin due to lots of data in the systemd journal.
When we looked at the code for fluent-bit we noticed that the systemd plugin supports the `Mem_Buf_Limit` option, but it is not documented.
Adding `Mem_Buf_Limit` with appropriate value to our fluent-bit config solved our OOM problems.

Any reasons this option has been left out of the systemd plugin docs?

**Comment by edsiper** [comment]
Note that mem_buf_limit is an option applicable to ALL input plugins, you can read more about that feature here:

- https://docs.fluentbit.io/manual/configuration/backpressure
- https://docs.fluentbit.io/manual/configuration/memory_usage
