### ISSUE TITLE
tail logrotate copytruncate documentation

### ISSUE THREAD

**Issue by RobinNil** [fluent/fluent-bit-docs#182]
From discussions in https://github.com/fluent/fluent-bit/issues/375, it seems that `tail` has worked with `logrotate` `copytruncate` option with fluent-bit version 0.12.15

The current documentation (https://docs.fluentbit.io/manual/v/1.2/input/tail, accessed on 2019-06-28 17:21:52 ET) seems to indicate that `logrotate` `copytruncate` mode is not supported.

I could not find any mention of `trunc`  in the release announcements since 0.12.16:
```
for v in v0.12.{16..19} v0.13.{0..8} v0.14.{0..9} v.1.0.{0..6} v1.1.{0..3} v.1.2.0; do 
    curl -s https://fluentbit.io/announcements/$v/ | grep trunc ; 
done
```

`git log -p input/tail.md` seems to indicate that the `copytruncate` line has never been updated to reflect that it was supported with version v0.12.15.

If `logrotate` `copytruncate` is supported now, may we update the documentation?

**Comment by edsiper** [comment]
thanks for your comments, the docs have been updated:

https://docs.fluentbit.io/manual/input/tail
