### ISSUE TITLE
getting_started/parser.md refers to missing ../parser/README.md

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit-docs#19]
From getting_started/parser.md#L28
```
Parsers are fully configurable, for more details please refer to the [Parsers](../parser/README.md) section.
```
The file `../parser/README.md` does not exist.

**Comment by edsiper** [comment]
thanks for noticing this issue. I pushed a temporal page in the meanwhile the content is created.

**Comment by StevenACoffman** [comment]
Thank you for all your good work!

**Comment by edsiper** [comment]
Fixed: http://fluentbit.io/documentation/0.11/parser/
