### ISSUE TITLE
Add old version warning header on documentation of 0.12

### ISSUE THREAD

**Issue by tobiasmuehl** [fluent/fluent-bit-docs#192]
For some search terms on Google the documentation of version 0.12 hosted at https://fluentbit.io/documentation/0.12/ ranks above the recent documentation. Would be nice to have a non-intrusive banner explaining that the documentation is for an outdated version, with a link to the most recent version.

**Comment by tobiasmuehl** [comment]
![Example](https://i.imgur.com/dQ6Wbsh.png)

**Comment by edsiper** [comment]
thanks, I will see how to fix that.

**Comment by lecaros** [comment]
I did some searches to verify. The results point to the latest version (i.e., URL without the version on it). Also, the link mentioned redirects to the latest version. Thus, closing this one for now.
Thanks @tobiasmuehl for reporting this!
