### ISSUE TITLE
Missing Stream_File field description in Service

### ISSUE THREAD

**Issue by loic35** [fluent/fluent-bit-docs#209]
Streams_File is mentioned in sample StreamProcessor page but not described in Service Page:
[SERVICE]
    Flush        1
    Log_Level    info
    Streams_File stream_processor.conf

**Comment by lecaros** [comment]
I can see the documentation in https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file#config_section and https://docs.fluentbit.io/manual/stream-processing/introduction
