### ISSUE TITLE
Config_Watch documented but seems unimplemented

### ISSUE THREAD

**Issue by sysadmind** [fluent/fluent-bit-docs#210]
On the [service documentation page](https://github.com/fluent/fluent-bit-docs/blob/master/service/README.md) there is a documented option `Config_Watch` that does not appear to work from my testing. It does appear to be a requested option though as I know I would love it for watching kubernetes configmap changes: fluent/fluent-bit#365

I did a bit of research and while my C isn't very good, I don't think that this config value is actually defined or implemented in the code: https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c

I assume this should be removed, but I'm not familiar enough with the project to know for sure.

**Comment by edsiper** [comment]
that feature was not merged, sorry about the confusion, the docs are up to date now

**Comment by BBenni** [comment]
Could you quickly elaborate _why_ the feature was not merged actually? Thank you.
