### ISSUE TITLE
No documentation on output:firehose

### ISSUE THREAD

**Issue by ppeterson-evotek** [fluent/fluent-bit-docs#214]
Docker image:
FROM fluent/fluent-bit:1.2-debug

output:
[OUTPUT]
    Name firehose
    Match *
    delivery_stream stream-name
    region us-east-1

Now I'm not complaining that it works, it works to transmit, just that i need extra configuration and there's no documentation on what the output params are.

**Comment by nigels-com** [comment]
Does not seem to be there in 1.3.
Can you confirm that?

**Comment by lecaros** [comment]
closing this as it's for a very old version
