### ISSUE TITLE
Not Clear How to Get Output of "Counter" to a File

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit-docs#217]
The example in the documentation shows:

[OUTPUT]
    Name  counter
    Match *

But how can we send the result of a Counter to a file?

**Comment by nigels-com** [comment]
That does not seem to be implemented for counter output plugin.
You could file an Feature Request with some further details, such as the use case.
https://github.com/fluent/fluent-bit/issues/new/choose

**Comment by lecaros** [comment]
@kaizen1 do you still need this? I couldn't find any feature request logged in the fluent-bit repo.
