### ISSUE TITLE
Document new docker input plugin

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit-docs#222]
Docker input plugin landed in v1.3 release but it misses documentation:

ref: https://github.com/fluent/fluent-bit/commit/d19be0d7651eb2463e95ffbca9295bde95f50567

**Comment by edsiper** [comment]
assigned to: @fujimotos

**Comment by fujimotos** [comment]
@edsiper I've just noticed this ticket. Will work on shortly.
