### ISSUE TITLE
Docs Have Some Nonsensical English in Important Section

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit-docs#223]
From:

https://docs.fluentbit.io/manual/configuration/file#config_input

These make very little sense in English. So it's not clear what is trying to be conveyed.

```
Match
It sets a pattern to match certain records Tag. It's case sensitive and support the star (*) character as a wildcard.

Match_Regex
It sets a pattern to match certain records Tag.
```

**Comment by lecaros** [comment]
I couldn't find the text in the latest version. I am closing it.
