### ISSUE TITLE
Fluent-bit dns usage question

### ISSUE THREAD

**Issue by lexa500** [fluent/fluent-bit-docs#226]
Hi, can you give some light on dns resolving question. 
We have a fluentd with dns name like fluentd.our.domain (ip x.x.x.x). this dns name is set in fluent-bit config, so everything works flawlessly. 
Now we want to switch ip to a new one. do we have to restart fluent-bit in order to re-resolve to new ip or it will just resolve as soon as the dns will propagate changes? Or does it take system-wide resolving info?

**Comment by edsiper** [comment]
Fluent Bit uses the system DNS lookup interface, so Fluent Bit always ask the system first and uses that value.

**Comment by omripmx** [comment]
Hi @edsiper , I'm having the same issue when changing the IP of the domain which is the output host for fluentbit.
Restart of fluentbit container helps, but I would like to understand if I can make fluentbit re-resolve the IP address of the domain dynamically or every X time.
