### ISSUE TITLE
Let's clarify if filter plugins can *drop* records or not

### ISSUE THREAD

**Issue by jgehrcke** [fluent/fluent-bit-docs#234]
For filters, very briefly described in https://docs.fluentbit.io/manual/getting_started/filter -- it is unclear what happens when a filter does not match a record. Does it mean the record is dropped or passed along unaltered?

Specifc example: if I use only the kubernetes filter with `Match kube.*` -- will records not having a tag starting with `kube.` be dropped?

Once this is clear to me I am happy to document that.

**Comment by fujimotos** [comment]
> Specifc example: if I use only the kubernetes filter with Match kube.* -- will records not having a tag starting with kube. be dropped?

No, it won't be dropped. Filters are only applied to records having a tag that
matches the regex. So in your case, records other than `kube.xxx` will just pass.
