### ISSUE TITLE
Output template format can't show the original content

### ISSUE THREAD

**Issue by Rice-tt** [fluent/fluent-bit-docs#236]
I collect verbose log and want to write in to a file. Default(out_file) and plain format work for me, but I don't want to change the format(no tag and timestamp). I try to use template format. However, it cannot show the original content.

My config of output part:
```
[OUTPUT]
    Name file
    Format template 
    #Template {message} (default: '{time} {message}')
    Path result.txt
```
result.txt
```
1573528176.966284 {message}
1573528176.966291 {message}
1573528176.966298 {message}
1573528176.966305 {message}
1573528176.966311 {message}
```

**Comment by fujimotos** [comment]
> 1573528176.966311 {message}

Probability is that you do not have the "message" field in your record.

What you need to do is to tweak the template string to match the actual
format of your log data. For example, if you have log records like:

    {"time": 157353212, "log": "foo"}

... then you need to set the `Template` option as follows:

    Template {log}

**Comment by Rice-tt** [comment]
> > 1573528176.966311 {message}
> 
> Probability is that you do not have the "message" field in your record.
> 
> What you need to do is to tweak the template string to match the actual
> format of your log data. For example, if you have log records like:
> 
> ```
> {"time": 157353212, "log": "foo"}
> ```
> 
> ... then you need to set the `Template` option as follows:
> 
> ```
> Template {log}
> ```

Thanks a lot!
