### ISSUE TITLE
Unit of 1024 byte

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit-docs#26]
https://github.com/fluent/fluent-bit-docs/blob/900f0f5181d20da3836954f1ba0ad7d0370e15cd/configuration/unit_sizes.md

Just FYI.
Recently, the units (a power of 1024) are defined as "*bibyte(*iB)".
e.g. http://physics.nist.gov/cuu/Units/binary.html

1024 byte = 1 kibibyte (KiB)
1024 * 1024 byte = 1 mebibyte (MiB)
1024 * 1024 * 1024 byte = 1 gibibyte (GiB)

Of course, we traditionally use "kilo"byte as 1024bytes and a lot of people may be familiar with it.

Do we need to fix them ?

**Comment by edsiper** [comment]
we are following Docker nomenclature: 

https://docs.docker.com/engine/admin/logging/json-file/#usage

to avoid typos and make it easier k, m and g should be fine (need to fix the upper/lower case stuff only)

**Comment by nokute78** [comment]
@edsiper Thanks, but json file driver of docker treats 'k' as 1000 byte.

docker defines unit size in size.go.
https://github.com/moby/moby/blob/master/vendor/github.com/docker/go-units/size.go

"HumanSize" of unit is 1000. "BytesSize" of unit is 1024.

json-file driver uses Humansize.
https://github.com/moby/moby/blob/master/daemon/logger/jsonfilelog/jsonfilelog.go#L48

**Comment by edsiper** [comment]
you are totally right :)

so they should be managed in decimal (KB = 1000), where k or K is to refer to KB:

- k, K = KB 
- m, M = MB
- g, G = GB

**Comment by edsiper** [comment]
yep.

**Comment by edsiper** [comment]
I am still thinking, people often use k, m, G, m.. but having a unit of 1000 bytes as a base is not optimal for a memory based optimization, setting 32k = 32000 bytes is not better than 32768 (based on 1024 bytes)

**Comment by nokute78** [comment]
I think it's better to be clear the policy of fluentbit.

Following some project policy? or technical reason?
I prefer technical way :)

**Comment by nokute78** [comment]
JFYI.
dd(1) treats unit like this.

"1MB"=1000 * 1000
"1MiB"=1024 * 1024
"1M" = 1024 * 1024
"1Mi"  is invalid.

```
$ dd if=/dev/zero of=zero.bat bs=1MB count=1
1+0 records in
1+0 records out
1000000 bytes (1.0 MB) copied, 0.010864 s, 92.0 MB/s
```

```
$ dd if=/dev/zero of=zero.bat bs=1MiB count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.0036835 s, 285 MB/s
```


```
dd if=/dev/zero of=zero.bat bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00594892 s, 176 MB/s
```

```
$ dd if=/dev/zero of=zero.bat bs=1Mi count=1
dd: invalid number `1Mi'
```

**Comment by edsiper** [comment]
that looks better

**Comment by nokute78** [comment]
Close.

The unit policy is defined at https://github.com/fluent/fluent-bit/issues/325.
And document is fixed by https://github.com/fluent/fluent-bit-docs/commit/78218ed1d1344ec5cd244a8120b1c3c16b029ff8
