### ISSUE TITLE
[2020/02/10 01:24:27] [error] [src/flb_config.c:128 errno=12] Cannot allocate memory

### ISSUE THREAD

**Issue by strictnerd** [fluent/fluent-bit-docs#264]
[root@k8s-master src]#  docker run -ti fluent/fluent-bit:1.3 /fluent-bit/bin/fluent-bit -i cpu -o stdout -f 1
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[2020/02/10 01:24:27] [error] [src/flb_config.c:128 errno=12] Cannot allocate memory

[root@k8s-master src]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (AltArch)

**Comment by edsiper** [comment]
is this Arm64v8 or x86_64 ?
