### ISSUE TITLE
Variables not working on parsers.conf

### ISSUE THREAD

**Issue by daspn** [fluent/fluent-bit-docs#269]
Hi everyone,

Is this configuration supposed to work?
### /fluent-bit/etc/parsers.conf
```
[PARSER]
    Name my_parser`
    Format regex`
    Regex ${MY_REGEX}
```
I'm trying to inject the regex via environment variable but it does not seem to work. 
```
export MY_REGEX='^(?<dummy>.+)$'
/fluent-bit/bin/fluent-bit -R /fluent-bit/etc/parsers.conf -i forward -F parser -p 'Match=*' -p 'Key_Name=log' -p 'Parser=my_parser' -o stdout -p 'Match=*'
```
If I hardcode the regex the parser works just fine:
```
[PARSER]
    Name my_parser
    Format regex
    Regex ^(?<dummy>.+)$
```
Thanks in advance.

**Comment by fujimotos** [comment]
> I'm trying to inject the regex via environment variable but it does not seem to work.

@daspn  AFAIK, Fluent Bit has no such feature that interpolate `Regex` configuration
from environment variables, which means it simply does not work that way.
