### ISSUE TITLE
Fluent Bit td-agent-bit package for Windows are not access either ZIP archive or EXE installer

### ISSUE THREAD

**Issue by vadymzagorodko** [fluent/fluent-bit-docs#273]
Hi team, 
There's no possibility to download td-agent-bit package for Windows either from GitHub 
 (https://github.com/fluent/fluent-bit-docs/blob/1.3/installation/windows.md)
or from fluenbit.io site.

**Comment by edsiper** [comment]
not longer an issue:

https://docs.fluentbit.io/manual/installation/windows
