### ISSUE TITLE
Disk input doc lacks info about units

### ISSUE THREAD

**Issue by PiotrKozimor** [fluent/fluent-bit-docs#275]
The documentation of [disk input](https://github.com/fluent/fluent-bit-docs/blob/1.3/input/disk.md) lacks info about `read_size` and `write_size`. Can any provide some clarification on unit? Then I may create table similiar to one in [cpu input](https://github.com/fluent/fluent-bit-docs/blob/1.3/input/cpu.md) and submit pull requests.

**Comment by nokute78** [comment]
@PiotrKozimor 
The unit is byte.

Just FYI.

read_size = sectors read * 512 byte.
write_size = sectors written * 512 byte.

sectors read/written are came from `/proc/diskstats`.
We use fixed sector size (=512byte), but it is not good..

The document of `/proc/diskstats` is here.
https://www.kernel.org/doc/Documentation/iostats.txt

```
Field  3 -- # of sectors read
    This is the total number of sectors read successfully.
```
```
Field  7 -- # of sectors written
    This is the total number of sectors written successfully.
```
