### ISSUE TITLE
input forward plugin has content about output forward plugin

### ISSUE THREAD

**Issue by JensErat** [fluent/fluent-bit-docs#284]
Looks like there was a copy/paste error when refactoring the documentation structure for 1.4: the input forward plugin docs have now the old output forward plugin contents.

https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/inputs/forward.md

**Comment by nokute78** [comment]
@JensErat Thank you for reporting issue.
I sent a patch #295.

**Comment by ishigoya** [comment]
This issue is also occurring in the documentation for version 1.5.
