### ISSUE TITLE
How is a Parser specified?

### ISSUE THREAD

**Issue by planetmarshall** [fluent/fluent-bit-docs#301]
I can't find any explanation in the [Parsers](https://docs.fluentbit.io/manual/pipeline/parsers) section as to how a Parser is actually specified in a configuration.

For example, if I want to use the `docker` parser, where would I specify this?

**Comment by shogo82148** [comment]
Some input plugin have the `Parser` parameter. https://docs.fluentbit.io/manual/pipeline/inputs/tail
Parsers can be used here.
