### ISSUE TITLE
Unit size documentation: description and examples do not match

### ISSUE THREAD

**Issue by JensErat** [fluent/fluent-bit-docs#308]
I just stumbled about a typo in the unit size table, but then realized that description and example seem to contradict (1024 vs 1000).

Which of the variants is true?

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/unit-sizes

| Suffix | Description | Example | Note | 
| :--- | :--- | :--- | --- |
|  | When a suffix is **not** specified, it's assumed that the value given is a bytes representation. | Specifying a value of 32000, means 32000 bytes |
| k, K, KB, kb | Kilobyte: a unit of memory equal to 1,000 bytes. | 32k means 3278 bytes. | totally weird, 32758 or 32000 | 
| m, M, MB, mb | Megabyte: a unit of memory equal to 1,000,000 bytes | 1M means 1024000 bytes | from description I would expect 1000000 bytes | 
| g, G, GB, gb | Gigabyte: a unit of memory equal to 1,000,000,000 bytes | 1G means 1024000000 bytes | same here, just some more 0s |

**Comment by edsiper** [comment]
thanks for catching that.

Fixed on af42774173f66dfdb7ffca544d8f1371fb83a916
