### ISSUE TITLE
Missing abstract about parser plugin 

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit-docs#329]
This page is missing on v1.4 repos.
https://docs.fluentbit.io/manual/v/1.3/parser

So, some users can't find global parser configurations. (e.g. `Types` property)
https://github.com/fluent/fluent-bit/pull/310#issuecomment-649061837

**Comment by elenacbc** [comment]
@nokute78 Sorry for the delayed response. Should this page be added only on v1.4 or all next versions too?
