### ISSUE TITLE
Missing Param

### ISSUE THREAD

**Issue by hetile-ssense** [fluent/fluent-bit-docs#34]
The following parameter is supported (and quite usefull) but not documented

Parser | Specify the name of a parser to interpret the entry as a structured message

**Comment by edsiper** [comment]
Note that not all input plugins support a native parser interface, the only one available are [Tail](http://fluentbit.io/documentation/0.11/input/tail.html) and [Syslog](http://fluentbit.io/documentation/0.11/input/syslog.html).

In the upcoming 0.12 release, there is a new Filter called parser that extend the functionality to all data generated by input plugins.

**Comment by edsiper** [comment]
Now I get it, option was undocumented on 0.11 docs, just fixed. 

thanks again.
