### ISSUE TITLE
The v1.4 input plugin page includes a link to an output plugin

### ISSUE THREAD

**Issue by ishigoya** [fluent/fluent-bit-docs#343]
The [v1.4 input plugin page](https://docs.fluentbit.io/manual/v/1.4/pipeline/inputs) includes a link to the output forward plugin, instead of the input forward plugin.

![1 4-forward](https://user-images.githubusercontent.com/16798645/87986480-23e3b280-cb18-11ea-95bb-ddf319bdc2d0.png)

Possibly related to #284

**Comment by championshuttler** [comment]
Thanks for filing just noticed that 1.5 docs also have output forward docs, made a PR
