### ISSUE TITLE
pipeline/inputs/tail.md has a broken link to Unit Size specification

### ISSUE THREAD

**Issue by bmarkowww** [fluent/fluent-bit-docs#356]
**Buffer_Chunk_Size** and **Buffer_Max_Size** parameters descriptions of input tail plugin have a broken link to Unit Size specification

https://github.com/fluent/fluent-bit-docs/tree/00bb8cbd96cc06988ff3e51b4933e16e49206c70/pipeline/configuration/unit_sizes.md

**Comment by pranavmarla** [comment]
FYI, this is the correct Unit Size link:
https://github.com/fluent/fluent-bit-docs/blob/master/administration/configuring-fluent-bit/unit-sizes.md
