### ISSUE TITLE
Elasticsearch output

### ISSUE THREAD

**Issue by ogerasymenko** [fluent/fluent-bit-docs#357]
Hi there. First of all this is not real issue - instead question.

In documentation  of es output plugin written:

```
Key  | Description |  default
----------------------------------------------------------------------------
Host | IP address or hostname of the target Elasticsearch instance | 127.0.0.1
```
As I understand in 'host' section I can write only one IP/DNS address of ES instance? 
Or it is possible to set multiple addresses with purpose of load balancing?

**Comment by elenacbc** [comment]
@ogerasymenko Sorry for the delayed response. I believe this question is better suited to lack or stackoverflow.
