### ISSUE TITLE
Stdout output plugin appears in Filters section

### ISSUE THREAD

**Issue by raine** [fluent/fluent-bit-docs#358]
Pretty sure this should only be listed in Outputs.

https://docs.fluentbit.io/manual/pipeline/filters/standard-output

![image](https://user-images.githubusercontent.com/11027/90120523-802aa280-dd63-11ea-97a5-a90c8a832be1.png)

**Comment by elenacbc** [comment]
@raine Sorry for the delayed response. I will consult this and delete the page if necessary. Thank you for the suggestion.

**Comment by patrick-stephens** [comment]
There is a `stdout` filter as well as an output: it's useful to debug output between filter stages.
