### ISSUE TITLE
make the right scrollbar wider

### ISSUE THREAD

**Issue by trondhindenes** [fluent/fluent-bit-docs#385]
The left scrollbar in https://docs.fluentbit.io/ is annoyingly narrow. Could we make it wider so it's easier to drag up and down?

**Comment by trondhindenes** [comment]
I just noticed that on my laptop touchpad, two-finger scrolling is able to scroll up and down the left menu, making the width of the scrollbar less of an issue. However, on my "regular" mouse, the scrollwheel always affects the center content, so I'm forced to drag the scrollbar to move the left menu up and down. Very weird.

**Comment by mickeypash** [comment]
Hey @trondhindenes this is a weird one.

What browser and OS are you running?
I'm on MacOS and the scroll bar is the same as any other one.

**Comment by trondhindenes** [comment]
Hi, thanks for following up. This might have been a bug in Chrome or something, I tested again and it's fine now. Both Chrome and Chromium on Ubuntu 22.04 work as intended.

**Comment by mickeypash** [comment]
I guess you can close the issue before the bot :)
