### ISSUE TITLE
Input forward plugin TLS

### ISSUE THREAD

**Issue by emilianoorengo** [fluent/fluent-bit-docs#404]
Hi guys,

I am trying to replace a fluentd pod with fluent-bit. It works as as log forwarder. I also using the Splunk plugin as output but I can't find the a way to secure the input with TLS. Could you please confirm is this feature available? Thanks in advance!

**Comment by agup006** [comment]
This feature does not exist yet, it is in the pipe, no firm ETA (https://github.com/fluent/fluent-bit/issues/2772)

**Comment by agup006** [comment]
Closing in doc repo - I've linked the Fluent Bit repo above
