### ISSUE TITLE
Incorrect links in Release Notes

### ISSUE THREAD

**Issue by shogo82148** [fluent/fluent-bit-docs#406]
Hi. I don't know here is right place to report, but I found incorrect links in https://fluentbit.io/announcements/

![image](https://user-images.githubusercontent.com/1157344/96711280-47005580-13d8-11eb-9683-628b0152e315.png)

It is in the "Fluent Bit v1.6 Series" section, so "Fluent Bit v1.5" should be "Fluent Bit v1.6". And it points [the v1.3 branch](https://github.com/fluent/fluent-bit/tree/1.3),it should point [the v1.6 branch](https://github.com/fluent/fluent-bit/tree/1.6).

Screenshots of my Developer Console is here.

![image](https://user-images.githubusercontent.com/1157344/96710748-72367500-13d7-11eb-8d9c-b178366110da.png)

```diff
-<a href="https://github.com/fluent/fluent-bit/tree/1.3">Fluent Bit v1.5</a>
+<a href="https://github.com/fluent/fluent-bit/tree/1.6">Fluent Bit v1.6</a>
```

![image](https://user-images.githubusercontent.com/1157344/96711005-d48f7580-13d7-11eb-919c-eaf999dea167.png)

```diff
-<a href="https://github.com/fluent/fluent-bit/tree/1.3">Fluent Bit v1.5</a>
+<a href="https://github.com/fluent/fluent-bit/tree/1.5">Fluent Bit v1.5</a>
```

![image](https://user-images.githubusercontent.com/1157344/96711152-128c9980-13d8-11eb-9e53-1e36531b6c3e.png)

```diff
-<a href="https://github.com/fluent/fluent-bit/tree/1.3">Fluent Bit v1.4</a>
+<a href="https://github.com/fluent/fluent-bit/tree/1.4">Fluent Bit v1.4</a>
```

**Comment by lecaros** [comment]
No longer valid
