### ISSUE TITLE
Filter the input plugin for the "tail" and "forward"

### ISSUE THREAD

**Issue by chikinchoi** [fluent/fluent-bit-docs#416]
Hi all,

I am using the fluent-bit to send logs to an external fluentd. There are two sources will send logs to the fluent-bit which are ecs and eks. The ECS will send logs by the "forward" plugin and the EKS send logs by using "tail" plugin
I have hard-coded the Path in the tail plugin, but when I send logs by ECS, the fluent-bit will read the "Path" value in the tail plugin anyway. Therefore, it will trigger the error "read error, check permissions: /var/log/ekslog/*.log".
May I know is there any ways to filter the Input to use different plugin? If not, is there any way to ignore the read error when the log file is not found?
Thank you!

**Comment by elenacbc** [comment]
Hi @chikinchoi sorry for the late response. I believe this issue is better suited for fluent-bit repo, slack or stackoverflow rather than fluent-bit docs repo.
