### ISSUE TITLE
Broken links in the Upstream page in fluentd docs

### ISSUE THREAD

**Issue by thamidurm** [fluent/fluent-bit-docs#420]
Hello. I noticed that all links in the [upstream servers page ](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/upstream-servers)of the fluentd documentation are broken.

For instance the link to  the "output plugins" section is pointing to [here](https://github.com/fluent/fluent-bit-docs/tree/5f926fd1330690179b8c1edab90d672699599ec7/administration/output/README.md), when it should point to [here](https://docs.fluentbit.io/manual/pipeline/outputs).

**Comment by agup006** [comment]
Thanks for reporting @thamidurm, I've fixed this link and it should be deployed momentarily
