### ISSUE TITLE
Inclusion of bash prompt character in copy widget for online documentation

### ISSUE THREAD

**Issue by linxcat** [fluent/fluent-bit-docs#422]
This page: https://docs.fluentbit.io/manual/installation/linux/amazon-linux
Coded here: https://github.com/fluent/fluent-bit-docs/blob/1.6/installation/linux/amazon-linux.md

Has a widget that auto-copies the code blocks. It copies the "$" from the script block, making the command invalid. It should not be included as part of the block. This is the case on the latter 3 blocks

**Comment by linxcat** [comment]
Seperately, the last block is totally useless, since it's an example return and thus copying it is meaningless

**Comment by agup006** [comment]
Thanks for submitting the issue @linxcat , this is a good point - we generally are using markdown format and the copy is added automatically as part of the GitBook featureset, we can look into only making the copy button available when there is truly a copy and paste motion that can be done.
