### ISSUE TITLE
New 'read_from_head' option is not documented

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit-docs#425]
In [v1.6.0](https://fluentbit.io/announcements/v1.6.0/), a new option was introduced for the Tail input plugin: `read_from_head`

However, although it's mentioned in the [v1.6.0 announcement](https://fluentbit.io/announcements/v1.6.0/), it is not mentioned in the Tail plugin's [documentation](https://docs.fluentbit.io/manual/pipeline/inputs/tail).

**Comment by agup006** [comment]
Thanks for submitting the issue @pranavmarla , I see the read_from_head as a configuration parameter - are you saying it should have it's own section?

**Comment by pranavmarla** [comment]
Hey @agup006 , it looks like @edsiper [fixed this](https://github.com/fluent/fluent-bit-docs/commit/a3c6b7b9e78e61099bd325e265feb4de54df9424) a few days ago, which is why you can now see `read_from_head` in the Tail plugin's [documentation](https://docs.fluentbit.io/manual/pipeline/inputs/tail). Please feel free to close this issue now.

And thanks for the prompt fix @edsiper!

**Comment by agup006** [comment]
Great to hear, I've closed.
