### ISSUE TITLE
Command not found for fluent-bit after following the docs

### ISSUE THREAD

**Issue by mgcrea** [fluent/fluent-bit-docs#428]
Not sure what I missed but just completed the install guide on ubuntu 18.04 and after installing adding the gpg key, apt source and installing `td-agent-bit`, I still can't run `fluent-bit`:

```
# fluent-bit 

Command 'fluent-bit' not found, but can be installed with:

snap install fluent-bit
# dpkg -l | grep td-agent-bit
ii  td-agent-bit                           1.6.8                                           amd64        Fast data collector for Linux
```

**Comment by edsiper** [comment]
The td-agent-bit package provides the binary with name "td-agent-bit" instead of "fluent-bit"

**Comment by mgcrea** [comment]
Unfortunately it does not work either:

```
# td-agent-bit
td-agent-bit: command not found
# apt install td-agent-bit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
td-agent-bit is already the newest version (1.6.8).
```

**Comment by agup006** [comment]
Thanks for submitting. `td-agent-bit` is not a command that is installed. It is instead registered as a service that you can use the following commands to interact with. 

```
# start td-agent-bit
sudo service td-agent-bit start

# get td-agent-bit status
sudo service td-agent-bit status
```

If you want to link the binary you can create a symlink with the td-agent-bit binary that is installed in `/opt/td-agent-bit/`. Closing for now, please re-open if there is something else that you are looking for

https://docs.fluentbit.io/manual/installation/linux/ubuntu
