### ISSUE TITLE
Having more examples for Tail input plugin documentation

### ISSUE THREAD

**Issue by alitoufighi** [fluent/fluent-bit-docs#433]
Hi.
I believe the Tail input plugin is the most used plugin of Fluent-Bit. However, the example configuration is very very basic and doesn't include any complicated features. I think at least the [Multiline Configuration Parameters](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline) can have an example to give more sense of the usage.

**Comment by agup006** [comment]
Hey @alitoufighi , I agree documentation could use a few more examples. I'm thinking of the following - let me know if there are others that you would like to see, we can look to add this week

1. Multi-line configuration
2. Reading a file from its beginning
3. Reading multiple files in a directory
4. Using DB to track multiple files / DB.sync example
5. Configuring buffers within tail plugin

**Comment by agup006** [comment]
Added an example for Multiline Configuration
