### ISSUE TITLE
Wrong default value for 'read_from_head' Tail param

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit-docs#441]
According to the Tail plugin's [documentation](https://docs.fluentbit.io/manual/pipeline/inputs/tail), the default value of the `read_from_head` param is `Off`.

However, according to the actual [code](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail.c#L491), its default value is `false`.

Is the Tail plugin's documentation wrong, or does Fluent Bit treat `Off` and `false` as equivalent?

**Comment by agup006** [comment]
Off and false are treated as equal. Though we should change to be the same as the code. I've changed the default
