### ISSUE TITLE
Documentation for Throttle filter not clear enough 

### ISSUE THREAD

**Issue by flankerqu** [fluent/fluent-bit-docs#465]
Throttle filter documentation's part about ignoring Window at start up phase is not clear enough. The current documentation explains indirectly that the window size is ignored at the beginning, which should be expressed more clearly and in a straight way:

`we received 1 message first second, 3 messages 2nd, and 5 3rd. As you can see, disregard that Window is actually 5, we use "slow" start to prevent overflooding during the startup.`

`average = 3, and not 1.8 if you calculate 0 for last 2 panes. `

"slow" start could be misleading, and the calculation example explains very indirect.

**Comment by elenacbc** [comment]
@flankerqu Thank you for the suggestion. We will take that into account.
