### ISSUE TITLE
Please stop to use apt-key for install documentation

### ISSUE THREAD

**Issue by kenhys** [fluent/fluent-bit-docs#472]
# Problem

Deprecated `apt-key` command is used to import key.
`apt-key` command will be removed sooner or later.

# Actual

https://github.com/fluent/fluent-bit-docs/blob/master/installation/linux/debian.md#server-gpg-key

```
$ wget -qO - https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
```

# Expected

Convert key to keyring and refer it by `signed-by` for example.

```
sudo apt-key --keyring ./fluent-bit-archive-keyring.gpg add fluentbit.key
```

```
$ cat /etc/apt/sources.list.d/fluent-bit.list 
deb [signed-by=/usr/share/keyrings/fluent-bit-archive-keyring.gpg] https://packages.fluentbit.io/debian/buster buster main
```

**Comment by agup006** [comment]
Thanks for reporting @kenhys, I also feel we should mimic Fluentd all-in-one.sh script for installation. Perhaps in that installation script we can change the way keys are installed

**Comment by patrick-stephens** [comment]
@agup006 want me to look at this more generally for packaging? I've added repo config files as well for the Yum-style repos so rather than creating a file you can just download it.
