### ISSUE TITLE
TLS / SSL Link Broken

### ISSUE THREAD

**Issue by mengtaosun** [fluent/fluent-bit-docs#475]
Hello folks - The TLS/SSL link in https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/outputs/kafka-rest-proxy.md is broken. (The same broken link also appears in https://docs.fluentbit.io/manual/pipeline/outputs/kafka-rest-proxy.)

**Comment by agup006** [comment]
Thanks for reporting @mengtaosun , I've fixed the broken link
