### ISSUE TITLE
What happened to SSL/TLS.md?

### ISSUE THREAD

**Issue by Followthevu** [fluent/fluent-bit-docs#487]
I am trying to figure out the http output and https and API endpoints but I cannot find the SSL/TLS documentation

**Comment by agup006** [comment]
Hi @Followthevu, is this what you are referring to https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls?

**Comment by agup006** [comment]
Ah I see we have a broken link on the output HTTP

**Comment by agup006** [comment]
Link fixed, merged, and deployed - this should be all fixed. Thank you for reporting!

**Comment by Followthevu** [comment]
this is the link thats broken for me https://github.com/fluent/fluent-bit-docs/tree/16f30161dc4c79d407cd9c586a0c6839d0969d97/pipeline/configuration/tls_ssl.md
