### ISSUE TITLE
Expose documentation link with version also for the latest version.

### ISSUE THREAD

**Issue by alzamon** [fluent/fluent-bit-docs#488]
https://docs.fluentbit.io/manual/v/1.7/ responds with not found. 

So there is no future-proof way to reference to documentation http page. 

I was going to write in my upgrade notes: 

"Upgraded from [1.4.0](https://docs.fluentbit.io/manual/v/1.4/) to [1.7.0](https://docs.fluentbit.io/manual/v/1.7/)"

If i write 
"Upgraded from [1.4.0](https://docs.fluentbit.io/manual/v/1.4/) to [1.7.0](https://docs.fluentbit.io/manual/)"

my documentation will soon be outdated.

**Comment by elenacbc** [comment]
@alzamon It now responds correctly, however, thank you for reporting this.
