### ISSUE TITLE
Ubuntu Package File Placement

### ISSUE THREAD

**Issue by sandstrom** [fluent/fluent-bit-docs#49]
*I didn't find a proper repo for the fluent-bit ubuntu package (td-agent-bit), so posting here.*

Packages (debian and ubuntu atleast, but probably other distros too), should not install stuff in `/opt`. 

Instead `/usr/share`, `/usr/lib`, `/usr/bin` etc should be used. It would be great if the `td-agent` and `td-agent-bit` packages would adhere to this principle.

`dpkg-query -L td-agent-bit` will list the current install locations. Can also be used to understand where other packages are storing their files.

**Comment by edsiper** [comment]
If someone want's to work on that change we are open to merge it (get a PR). For now I am closing this ticket since is not an issue associated to documentation.

**Comment by sandstrom** [comment]
@edsiper Can I reopen it somewhere else? There is also a "transfer issue" button you can use, to move this to a more appropriate place.

**Comment by edsiper** [comment]
it's opened again but I don't see that button.

**Comment by sandstrom** [comment]
Below is a screenshot. Maybe it's not rolled out everywhere yet (labeled as beta).

If you want I can reopen this in a new repo, what repo is a better fit for this?

![image](https://user-images.githubusercontent.com/122287/48062868-91747180-e1c3-11e8-8d1e-fe6042adc3bd.png)

**Comment by edsiper** [comment]
you should open a PR on fluent/fluent-bit.

**Comment by edsiper** [comment]
closing for now, please open a new one on fluent/fluent-bit.
