### ISSUE TITLE
Splunk output plugin: Data channel is missing

### ISSUE THREAD

**Issue by ardove** [fluent/fluent-bit-docs#496]
Hi there - I've been scouring the internet trying to figure out how to pump logs into splunk when "indexer acknowledgement" is enabled, but I can't seem to find anything specific to fluentbit in these docs or anywhere else. 

For some details on what indexer acknowledgement is, see here 
https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/AboutHECIDXAck

tl;dr -- it's  way for the HTTP Event Collector to alert the caller of a potentially problematic request BEFORE it goes into the processing pipeline (and my understanding is that it's a good idea to enable this in a production logging system). 

You'll note, from this page, that, when indexer acknowledgement is enabled AND splunk receives a request WITHOUT the data channel header on the http request, it returns an HTTP status code 400 with response body `{"text":"Data channel is missing","code":10}`. 
https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/UsetheHTTPEventCollector#Example_of_sending_data_to_HEC_with_an_HTTP_request

This is, in fact, the exact error I'm seeing in my fluentbit logs running in k8s, but I'm guessing that I'm just missing a key in configuration. 
```
[2021/03/23 16:33:29] [ warn] [output:splunk:splunk.2] http_status=400:
{"text":"Data channel is missing","code":10}
[2021/03/23 16:33:29] [ warn] [engine] failed to flush chunk '1-1616517162.556356447.flb', retry in 10 seconds: task_id=2, input=tail.1 > output=splunk.2
[2021/03/23 16:33:59] [ warn] [output:splunk:splunk.2] http_status=400:
{"text":"Data channel is missing","code":10}
[2021/03/23 16:33:59] [ warn] [engine] chunk '1-1616517162.556356447.flb' cannot be retried: task_id=2, input=tail.1 > output=splunk.
```

Is there a magic key that I need to put in my [Output] configuration or is that just not supported by the splunk plugin for fluentbit? If there is a key, can you please add a note about this in the splunk plugin documentation?

**Comment by ardove** [comment]
Pinging this thread -- anyone have answers?

**Comment by agup006** [comment]
I took a look at the Splunk documentation and it looks like Version 8.x will need a custom header to specify channel, I'm going to close this issue in the docs repo and use your linked issue 3314
