### ISSUE TITLE
Docs about tls.vhost are unclear

### ISSUE THREAD

**Issue by cedws** [fluent/fluent-bit-docs#507]
I'm experimenting with fluentbit to fluentd fowarding with TLS encryption using a self-signed certificate.

I struggled for a while to get fluentbit to connect to fluentd because it was rejecting the certificate:
```
X509 - Certificate verification failed, e.g. CRL, CA or signature check
```

Adding the `tls.vhost` option with the common name of the server certificate got it working:
```diff
[OUTPUT]
    ...
    tls         on
    tls.ca_file /blah/blah.crt
    tls.debug   4
+   tls.vhost   fluentd
```

In the docs `tls.vhost` is described as the `hostname to be used for TLS SNI extension`. 
```
If you are serving multiple hostnames on a single IP address (a.k.a. virtual hosting), you can make use of tls.vhost to connect to a specific hostname.
```

I ignored it because I am not using SNI or serving multiple hostnames on an address so this didn't seem to be relevant to me.

**Comment by elenacbc** [comment]
@cedws Sorry for the late response. We will change this in order to make things clearer. Thanks for the suggestion.
