### ISSUE TITLE
Older verison of fluentbit in documentation

### ISSUE THREAD

**Issue by ricgatti** [fluent/fluent-bit-docs#508]
Hi,

I'm trying to setup fluentbit version 1.7 on minikube but the version that I found on the manifest is
`fluent/fluent-bit:1.5`
and have an error with the config because I'm using the version 1.7 input config.
Is that correct the version 1.5 on documentation of the 1.7?

Kind regards,
Riccardo

**Comment by LeoWinterDE** [comment]
In the meantime, you can select the documentation version. Like https://docs.fluentbit.io/manual/v/1.5/ or https://docs.fluentbit.io/manual/v/1.7/

#close
