### ISSUE TITLE
Please support Google application default credentials, GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by rvandegrift** [fluent/fluent-bit-docs#515]
Providing credentials for the stackdriver output is harder than necessary due to not using their SDK's standard credential loading mechanisms.  This page provides a good overview of how that should work: https://cloud.google.com/docs/authentication/production

If that's not practical, it'd be great to at least be able to use the env var GOOGLE_APPLICATION_CREDENTIALS.

**Comment by nokute78** [comment]
Hi. This is a document repository.
If you request new feature, it is better to open issue at https://github.com/fluent/fluent-bit.

Thank you.

**Comment by rvandegrift** [comment]
oops!
