### ISSUE TITLE
Splunk plugin: New 'event_key' option is not documented

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit-docs#543]
In the Fluent Bit 1.7.5 [release notes](https://fluentbit.io/announcements/v1.7.5/), the following change is mentioned:
> Splunk (Output):
New event_key option and fixes for raw mode

However, the release notes do not contain any links to related pull requests, and the Splunk plugin [documentation](https://docs.fluentbit.io/manual/pipeline/outputs/splunk/) does not contain any reference to a new `event_key` option.

**Comment by agup006** [comment]
Aologies on no comment here, Thanks for reporting @pranavmarla  this appears to have been added afterwards. Closing

**Comment by pranavmarla** [comment]
No worries @agup006 , thanks for closing!
