### ISSUE TITLE
Http input plugin "Content-Type: application/json; charset=utf-8" not working

### ISSUE THREAD

**Issue by skasliwal-Liv** [fluent/fluent-bit-docs#547]
Hello, 
I am sending logs using serilog http sink to the http input of Fluentbit. The library is always adding the charset in the Content-Type header. ["Content-Type: application/json; charset=utf-8"]. The fluentbit http input plugin is not accepting this header and I am always getting the "error: invalid 'Content-Type'"
is there any way to allow the charset ?

Thanks

**Comment by agup006** [comment]
@skasliwal-Liv This issue is better suited for the fluent-bit repo vs. the documentation repo
