### ISSUE TITLE
Where is actual downloads are locate?

### ISSUE THREAD

**Issue by artisticcheese** [fluent/fluent-bit-docs#560]
I spent 15 mins where to actually download binaries. 
Page which is supposed to list downloads  (https://fluentbit.io/download/) in fact redirects to installation instructions (https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit) have only links to documentation how to install it once you are downloaded but there is no actual download links.

GET https://fluentbit.io/download/ HTTP/1.1
User-Agent: Fiddler
Host: fluentbit.io

HTTP/1.1 301 Moved Permanently
Date: Sat, 26 Jun 2021 20:58:58 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Sat, 26 Jun 2021 21:58:58 GMT
***Location: https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit***
cf-request-id: 0aebb768aa0000d286a4bd7000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 66595b544953d286-DFW
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400

0

![image](https://user-images.githubusercontent.com/13176884/123525570-50446f00-d697-11eb-9859-9a9253c0b417.png)

**Comment by amityagov** [comment]
@artisticcheese just scroll up on https://docs.fluentbit.io/manual/installation/windows#installing-from-zip-archive

**Comment by agup006** [comment]
I changed the piece in that doc to say from above similar to what @amityagov mentioned.
