### ISSUE TITLE
Health input plugin documentation is misleading

### ISSUE THREAD

**Issue by davidmukiibi** [fluent/fluent-bit-docs#562]
- The health input plugin is a little misleading. it should state that the port specified should be the same port the http server is running on and not hard coded port 80.
- I spent 3 days googling around and in slack channels trying to debug an error that came from that and a simple switch to port 2020, the same as the http server was the silver bullet.
- I'd like to edit the documentation myself to add that

**Comment by davidmukiibi** [comment]
I just checked in the open PRs and this is the same change I was gonna suggest.. https://github.com/fluent/fluent-bit-docs/pull/536
kindly merge it, it will save a lot of newbies a lot of time.

**Comment by agup006** [comment]
Hey @davidmukiibi thanks for filing an issue - I'm getting to this a bit late and I'm confused. The health input plugin does a TCP check on a remote plugin while the HTTP server mentioned in the second bullet reveals info about Fluent Bit's internals. We do also have a new Health API that is part of the PR referenced, though that is different from the Health Input Plugin
