### ISSUE TITLE
Hands On page examples do not work with versions >= 1.6

### ISSUE THREAD

**Issue by johnnybaloney** [fluent/fluent-bit-docs#569]
Just starting with Fluent Bit. I wanted to try it quickly so looked at the latest version's [Hands On page](https://docs.fluentbit.io/manual/stream-processing/getting-started/hands-on). It states:

> Requirements
> 
> The following tutorial requires the following software components:
>
>    ​Fluent Bit >= v1.2.0

The examples on the page use image versions 1.2 and 1.4.

The following works for 1.4 and 1.5:

```
$ docker run -ti -v `pwd`/sp-samples-1k.log:/sp-samples-1k.log fluent/fluent-bit:1.4 /fluent-bit/bin/fluent-bit -R /fluent-bit/etc/parsers.conf -i tail -p path=/sp-samples-1k.log -p parser=json -o stdout -f 1
```

When bumped to 1.6 or higher the sample log is not processed:

```
$ docker run -ti -v `pwd`/sp-samples-1k.log:/sp-samples-1k.log fluent/fluent-bit:1.6 /fluent-bit/bin/fluent-bit -R /fluent-bit/etc/parser
s.conf -i tail -p path=/sp-samples-1k.log -p parser=json -o stdout -f 1
Fluent Bit v1.6.10
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/07/13 10:42:23] [ info] [engine] started (pid=1)
[2021/07/13 10:42:23] [ info] [storage] version=1.0.6, initializing...
[2021/07/13 10:42:23] [ info] [storage] in-memory
[2021/07/13 10:42:23] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/07/13 10:42:23] [ info] [sp] stream processor started
[2021/07/13 10:42:23] [ info] [input:tail:tail.0] inotify_fs_add(): inode=8374917 watch_fd=1 name=/sp-samples-1k.log
```

**Comment by johnnybaloney** [comment]
Looks like the [Tail Input Plugin change in 1.6](https://docs.fluentbit.io/manual/installation/upgrade-notes#tail-input-plugin) is why I couldn't see any output. Including `-p read_from_head=true` in the command makes it appear.

**Comment by agup006** [comment]
Thanks for reporting @johnnybaloney, I updated with the latest version and added the read_from_head=true parameter to the examples
