### ISSUE TITLE
Fluent-bit 1.8 multline features undocumented

### ISSUE THREAD

**Issue by z0rc** [fluent/fluent-bit-docs#572]
https://fluentbit.io/announcements/v1.8.1/#new-multiline-core-feature

Tail's new options and whole [MULTILINE_PARSER] section aren't documented.

**Comment by lecaros** [comment]
hi @z0rc, I believe this is documented now. (see https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing). If you see that something's missing, please let us know.
