### ISSUE TITLE
it is possible to set multiple es addresses

### ISSUE THREAD

**Issue by hfczgo** [fluent/fluent-bit-docs#590]
example of es output plugin written:
[OUTPUT]
    Name  es
    Match *
    Host  192.168.2.3
    Port  9200
    Index my_index
    Type  my_type

it is possible to set multiple elasticsearch addresses with purpose of load balancing?

**Comment by elenacbc** [comment]
@hfczgo In order for your question to be answered correctly, please use slack, stackoverflow or fluent-bit repo.
