### ISSUE TITLE
Multiline Parser: Discrepancy over default flush timeout

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit-docs#595]
Relatively minor issue, but I noticed that there seems to be conflicting default values mentioned for the `flush_timeout` multiline parser parameter.

Specifically:

- As per the [multiline parsing doc](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing), the default is **5 seconds**
  > flush_timeout: Timeout in milliseconds to flush a non-terminated multiline buffer. Default is set to 5 seconds.

- As per the [comments](https://github.com/fluent/fluent-bit/blob/19690076e619f420e89539b6b795bc68401f9871/src/multiline/flb_ml_parser_docker.c#L89-L90) in the built-in Docker multiline parser code, the default is **0.5 seconds**
  > In case a message is not complete just wait until 500 milliseconds (0.5 second) and flush the buffer.

- As per the actual [multiline parser code](https://github.com/fluent/fluent-bit/blob/5451e40a1edac22460576a1f37f4149778001b51/include/fluent-bit/multiline/flb_ml.h#L48), the default is **4 seconds**
  > #define FLB_ML_FLUSH_TIMEOUT    4000 /* Flush timeout default (milliseconds) */

**Comment by elenacbc** [comment]
@pranavmarla Thanks for noticing. We will try to solve this.
