### ISSUE TITLE
Fix the record modifier page in version 1.7

### ISSUE THREAD

**Issue by tanagumo** [fluent/fluent-bit-docs#598]
I don't think that `record_modifier` plugin support `Allowlist_key` in version 1.7 (it seemed to be supported since v1.8.0).
So, the descripiton should be removed from the document for version 1.7.

**Comment by agup006** [comment]
@nokute78 would you happen to know what version this was released in? I thought we had it as part of a 1.7.x release, though we should specify in docs

**Comment by agup006** [comment]
Original Issue for ref: https://github.com/fluent/fluent-bit/issues/2701

**Comment by nokute78** [comment]
@agup006  The `Allowlist_key` feature is supported from v1.8.0-rc1, not for v1.7.x. @tanagumo is right.
So do we need to add like `the feature is supported from v1.8.0` ?

thttps://github.com/fluent/fluent-bit/commit/2dfd703393c216bb602724f6b17b181d87511ac6#diff-e4d9c809cce0b0762bd31f8c97a581720af8729b1a751bcaccf60f3bd0136f4f
