### ISSUE TITLE
Document new 'winstat' input

### ISSUE THREAD

**Issue by noahbailey** [fluent/fluent-bit-docs#631]
in_winstat was added to v1.8.x in this pull request: https://github.com/fluent/fluent-bit/pull/3525

It should be added to the inputs page in the manual: https://docs.fluentbit.io/manual/pipeline/inputs

A simple config example could be: 

```
[INPUT]
    Name    winstat
    Tag        windows.metrics
    Interval_sec  10
```

**Comment by agup006** [comment]
@fujimotos would you be able to add this as Windows Log Based Metrics input?

**Comment by jbongseo** [comment]
Before it is documented, refer to https://learn.microsoft.com/en-us/windows/win32/api/psapi/ns-psapi-performance_information for the meaing of each field.
