### ISSUE TITLE
Multiline missing actual parse example

### ISSUE THREAD

**Issue by squalou** [fluent/fluent-bit-docs#727]
Hi,

I'm struggling with "multiline" and I think the documentation is missing one example whare
- lines are indeed "joinded"
- THEN parsed to fields.

So far, following this documentation : 

https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace

It's easy enough to get for instance a full stack trace with its line breaks inside a "log" field.

But then what ?

No idea how to parse this log.
Spoiler alert : chaining another "filter parser" does not work, only the first line is parsed.

Real usecase would seem to be : 

step one : 

```
[1] tail.0: [1626736433.143570538, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
```

step two : obtain

```
{
  "time" : "Dec 14 06:41:08",
  "message" : "Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)"
 }

```

Additional context : I cannot change my "INPUT" configuration, hence **cannot** rely on     the `Multiline on` and `   Parser_Firstline multiline` approach.  I have to play with [FILTER] only. (AWS firelens context, not to enter in too many details)

**Comment by elenacbc** [comment]
@squalou Thanks for the suggestion. PRs are most welcome. We'll try to add a parse example.

**Comment by elenacbc** [comment]
Hi, @squalou. What lines other than the first ones are you trying to parse?

**Comment by elenacbc** [comment]
Hello, @squalou
> It’s easy enough to get for instance a full stack trace with its line breaks inside a “log” field.

Once you have the multiline part, you can create a Parser and use it in the configuration as a Filter Parser.
Here is an example:
```
[PARSER]
    Name            gh-727
    Format          regex
    Regex           ^(?<time>[a-zA-Z]+ \d+ \d+\:\d+\:\d+)(?<message>(.*\n^\s+at.*(\n\s+at.*)*))$
    time_keep       off
```
This is a Regex Parser. The regular expression in the field “regex” is made for the message you want to parse:
`^`: This matches the start of the line.
`(?<time>[a-zA-Z]+ \d+ \d+\:\d+\:\d+)`: This is a named capturing group, which matches a string with the format “Month Day Hour:Minute:Second”. The named capturing group allows you to refer to the matched text by its name “time”.
`(?<message>(.*\n^\s+at.*(\n\s+at.*)*))`: This is another named capturing group that matches the rest of the log message which are multiple lines, each of which starts with one or more whitespaces and the string “at”.
`$`: Finally, this matches the end of the line.
If you wish to create another custom regex visit the Regex Parser documentation [here](https://docs.fluentbit.io/manual/pipeline/parsers/regular-expression).

The Filter Parser in the configuration file would look like this:
```
[FILTER]
    Name            parser
    Match           *
    Key_Name        log
    Parser          gh-727
```
Field “name” in Parser must match field “parser” in the Filter.
Please visit the documentation on Filter Parser [here](https://docs.fluentbit.io/manual/pipeline/filters/parser) for more information.
