### ISSUE TITLE
Improvement of documentation for parsers

### ISSUE THREAD

**Issue by rufreakde** [fluent/fluent-bit-docs#833]
Hi all,

it would make the usage of parsers much simpler to understand if there would be some real world examples in the documentation. Please improve the documentation for fluent-bit parsers with the usual defaults which are
containered (cri) and docker:

https://docs.fluentbit.io/manual/v/1.4/pipeline/filters/parser

This seems to be not that easy to understand and examples found online are usually not that stable or outdated.
e.g.
https://github.com/microsoft/fluentbit-containerd-cri-o-json-log

CRI changes the log behaviour slightly it would be nice to have a solid default in the documentation for such a vastly used environment!
<img width="476" alt="Screenshot 2022-06-29 at 14 22 41" src="https://user-images.githubusercontent.com/28104368/176435224-16b8c0ad-f0b5-40e3-ab26-1d37fd636675.png">

# proposal 
Add an Examples section for a configuration with 3 examples:

## Common Parser Examples

1. Docker
2. Containered (CRI)
3. Complex Example working with both Docker + CRI

**Comment by elenacbc** [comment]
@rufreakde Thanks for the suggestion. PRs are most welcome. We'll try to add docs on that.
