### ISSUE TITLE
v0.13 documentation has the wrong Kubernetes filter fields

### ISSUE THREAD

**Issue by nikolay** [fluent/fluent-bit-docs#87]
The new property is just `Merge_Log`, but your documentation still has the old `Merge_JSON_Log`. Even your [Kubernetes example](https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/output/elasticsearch/fluent-bit-configmap.yaml#L41) uses the new property.

**Comment by edsiper** [comment]
thanks. fixed by 3974718
