### ISSUE TITLE
td-agent-bit default parsers is broken

### ISSUE THREAD

**Issue by venkat-rafay** [fluent/fluent-bit-docs#88]
The default `parsers.conf` available in `/etc/td-agent-bit/` now contains a new entry `crio` which fails validation.

Starting td-agent-bit with the following params throws an error:
```
/opt/td-agent-bit/bin/td-agent-bit -c fluentbit.conf -R /etc/td-agent-bit/parsers.conf
[2018/07/30 07:11:31] [error] [parser:crio] Invalid format Regex
```

**Comment by edsiper** [comment]
Fixed in 0.13.6 release, thanks again.
