### ISSUE TITLE
AWS credentials for multi-tenant setups

### ISSUE THREAD

**Issue by jroper** [fluent/fluent-bit-docs#892]
In multi-tenant cloud setups, the same Fluent Bit process may need to access AWS using different tenant provided AWS accounts. For example, we may want logs for tenant A's services to go to tenant A's CloudWatch account, and logs for tenant B's services to go to tenant B's CloudWatch account.

Currently it seems all the AWS plugins only support accessing AWS using one shared set of credentials. To support these multi-tenant setups, Fluent Bit plugins will need to support supplying AWS credentials per use of the plugin, so per output for example, via maybe directly configuring AWS key ids and secret settings, or specifying a file and maybe profile.

**Comment by elenacbc** [comment]
@jroper If you have a feature request on this issue, feel free to do it on fluent-bit repo instead of fluent-bit docs, thanks.
